function nl_diff_eqns = NL_diff_eqns(t,B_p,B_r,J_a,J_p,alpha_dot,g,l_p,m_p,r,tau,theta_dot)
%NL_diff_eqns
%    NL_DIFF_EQNS = NL_diff_eqns(T,B_p,B_r,J_a,J_p,ALPHA_DOT,G,L_P,M_P,R,TAU,THETA_DOT)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Mar-2023 19:05:35

t2 = alpha(t);
t3 = theta(t);
t6 = l_p.^2;
t4 = cos(t2);
t5 = sin(t2);
t7 = t2.*2.0;
t8 = diff(t2,t);
t9 = diff(t3,t);
t10 = diff(t2,t,t);
t11 = diff(t3,t,t);
t12 = m_p.*t6;
t13 = sin(t7);
nl_diff_eqns = [tau+t4.^2.*t12.*diff(t3,t,t)+l_p.*m_p.*r.*t4.*diff(t2,t,t) == B_r.*theta_dot+(J_a+t12+m_p.*r.^2).*diff(t3,t,t)+t12.*t13.*diff(t2,t).*diff(t3,t)+l_p.*m_p.*r.*t5.*diff(t2,t).^2;B_p.*alpha_dot.*2.0+(J_p+t12).*diff(t2,t,t).*2.0 == t12.*t13.*diff(t3,t).^2+g.*l_p.*m_p.*t5.*2.0+l_p.*m_p.*r.*t4.*diff(t3,t,t).*2.0];
