function [A,B,C,D] = SS_Matrices(B_p,B_r,J_a,J_p,K_g,R_m,eta_g,eta_m,g,k_m,k_t,l_p,m_p,r)
%SS_Matrices
%    [A,B,C,D] = SS_Matrices(B_p,B_r,J_a,J_p,K_g,R_m,ETA_G,ETA_M,G,K_M,K_T,L_P,M_P,R)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    04-Mar-2023 00:49:41

t2 = K_g.^2;
t3 = l_p.^2;
t4 = r.^2;
t5 = J_a.*J_p;
t6 = B_r.*R_m;
t7 = 1.0./R_m;
t8 = m_p.*t3;
t9 = m_p.*t4;
t14 = eta_g.*eta_m.*k_m.*k_t.*t2;
t10 = J_a.*t8;
t11 = J_p.*t9;
t12 = J_p+t8;
t13 = J_a+t9;
t15 = t6+t14;
t16 = t5+t10+t11;
t17 = 1.0./t16;
A = reshape([0.0,0.0,0.0,0.0,0.0,0.0,g.*m_p.*r.*t8.*t17,g.*l_p.*m_p.*t13.*t17,1.0,0.0,-t7.*t12.*t15.*t17,-l_p.*m_p.*r.*t7.*t15.*t17,0.0,1.0,B_p.*l_p.*m_p.*r.*t17.*(-1.0./2.0),B_p.*t13.*t17.*(-1.0./2.0)],[4,4]);
if nargout > 1
    B = [0.0;0.0;K_g.*eta_g.*eta_m.*k_t.*t7.*t12.*t17;K_g.*eta_g.*eta_m.*k_t.*l_p.*m_p.*r.*t7.*t17];
end
if nargout > 2
    C = reshape([1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0],[2,4]);
end
if nargout > 3
    D = [0.0;0.0];
end
