function xdot = Lin_eqns(t,x,V_m,th)
%Lin_eqns
%    STT_EQNS = Lin_eqns(B_p,B_r,J_a,J_p,K_g,R_m,V_m,ETA_G,ETA_M,G,K_M,K_T,L_P,M_P,R,x(2,1),x(3,1),x(4,1),X_DOT_1,X_DOT_2,X_DOT_3,X_DOT_4)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    18-Mar-2023 19:05:40
B_p = th(1,1);
B_r = th(2,1);
J_a = th(3,1);
J_p = th(4,1);
l_p = th(5,1);
m_p = th(6,1);
r = th(7,1);
g = th(8,1);
K_g = th(9,1);
R_m = th(10,1);
eta_g = th(11,1);
eta_m = th(12,1);
k_m = th(13,1);
k_t = th(14,1);

t2 = K_g.^2;
t3 = l_p.^2;
t4 = m_p.^2;
t5 = r.^2;
t6 = J_a.*J_p;
t7 = 1.0./R_m;
t8 = J_a.*m_p.*t3;
t9 = J_p.*m_p.*t5;
t10 = K_g.*V_m.*eta_g.*eta_m.*k_t.*t7;
t11 = eta_g.*eta_m.*k_m.*k_t.*t2.*t7.*x(3,1);
t12 = -t11;
t13 = t6+t8+t9;
t14 = 1.0./t13;
t15 = t10+t12;

xdot = zeros(4,1);

xdot(1,1) = x(3,1);
xdot(2,1) = x(4,1);
xdot(3,1) = t14.*(J_p.*t15+m_p.*t3.*t15)-t14.*x(3,1).*(B_r.*J_p+B_r.*m_p.*t3)+g.*r.*t3.*t4.*t14.*x(2,1)+B_p.*l_p.*m_p.*r.*t14.*x(4,1);
xdot(4,1) = -t14.*x(4,1).*(B_p.*J_a+B_p.*m_p.*t5)-t14.*x(2,1).*(g.*l_p.*t4.*t5+J_a.*g.*l_p.*m_p)-l_p.*m_p.*r.*t14.*t15+B_r.*l_p.*m_p.*r.*t14.*x(3,1);
