function nl_diff_eqns_ss = NL_eqns_Disturbance(B_p,B_r,J_a,J_p,M_d,g,l_p,m_p,r,tau,x_2,x_3,x_4,x_dot_1,x_dot_2,x_dot_3,x_dot_4)
%NL_eqns_Disturbance
%    NL_DIFF_EQNS_SS = NL_eqns_Disturbance(B_p,B_r,J_a,J_p,M_d,G,L_P,M_P,R,TAU,X_2,X_3,X_4,X_DOT_1,X_DOT_2,X_DOT_3,X_DOT_4)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    07-May-2023 08:47:27

t2 = cos(x_2);
t3 = sin(x_2);
t4 = l_p.^2;
t5 = l_p.^3;
t7 = m_p.^2;
t8 = r.^2;
t9 = x_2.*2.0;
t10 = x_3.^2;
t11 = x_4.^2;
t12 = J_a.*J_p;
t6 = t4.^2;
t13 = t2.^2;
t14 = sin(t9);
t15 = J_a.*m_p.*t4;
t16 = J_p.*m_p.*t4;
t17 = J_p.*m_p.*t8;
t20 = t4.*t7.*t8;
t18 = t6.*t7;
t19 = t13.*t16;
t24 = t13.*t20;
t21 = t13.*t18;
t22 = -t19;
t25 = -t24;
t23 = -t21;
t26 = t12+t15+t16+t17+t18+t20+t22+t23+t25;
t27 = 1.0./t26;
mt1 = [x_dot_1 == x_3;x_dot_2 == x_4;x_dot_3 == t27.*(J_p.*tau.*-2.0+B_r.*J_p.*x_3.*2.0-m_p.*t4.*tau.*2.0+t14.*t16.*x_3.*x_4.*2.0+t14.*t18.*x_3.*x_4.*2.0+B_r.*m_p.*t4.*x_3.*2.0-M_d.*l_p.*m_p.*r.*t2.*2.0+r.*t3.*t5.*t7.*t11.*2.0-g.*r.*t2.*t3.*t4.*t7.*2.0-r.*t2.*t5.*t7.*t10.*t14+B_p.*l_p.*m_p.*r.*t2.*x_4.*2.0+J_p.*l_p.*m_p.*r.*t3.*t11.*2.0).*(-1.0./2.0)];
mt2 = [x_dot_4 == (t27.*(J_a.*M_d.*2.0-B_p.*J_a.*x_4.*2.0+M_d.*m_p.*t4.*2.0+M_d.*m_p.*t8.*2.0+t10.*t14.*t15+t10.*t14.*t18+t10.*t14.*t20+t10.*t14.*t23-M_d.*m_p.*t4.*t13.*2.0+g.*t3.*t5.*t7.*2.0-t2.*t3.*t11.*t20.*2.0-B_p.*m_p.*t4.*x_4.*2.0-B_p.*m_p.*t8.*x_4.*2.0+J_a.*g.*l_p.*m_p.*t3.*2.0+B_p.*m_p.*t4.*t13.*x_4.*2.0+g.*l_p.*t3.*t7.*t8.*2.0+l_p.*m_p.*r.*t2.*tau.*2.0-g.*t3.*t5.*t7.*t13.*2.0-B_r.*l_p.*m_p.*r.*t2.*x_3.*2.0-r.*t2.*t5.*t7.*t14.*x_3.*x_4.*2.0))./2.0];
nl_diff_eqns_ss = [mt1;mt2];
