function x_dot = NL_eqns_EKF(x,V_m,th) %#codegen
%NL_eqns
%    NL_DIFF_EQNS_SS = NL_eqns(B_p,B_r,J_a,J_p,G,L_P,M_P,R,TAU,x(2,1),x(3,1),x(4,1),X_DOT_1,X_DOT_2,X_DOT_3,X_DOT_4)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    09-Mar-2023 15:34:15

B_p = th(1,1);
B_r = th(2,1);
J_a = th(3,1);
J_p = th(4,1);
l_p = th(5,1);
m_p = th(6,1);
r = th(7,1);
g = th(8,1);
K_g = th(9,1);
R_m = th(10,1);
eta_g = th(11,1);
eta_m = th(12,1);
k_m = th(13,1);
k_t = th(14,1);

tau = eta_g*K_g*eta_m*k_t*(V_m-K_g*k_m*x(3,1))/R_m; % motor torque expression-STATIC

t2 = cos(x(2,1));
t3 = sin(x(2,1));
t4 = l_p.^2;
t5 = l_p.^3;
t7 = m_p.^2;
t8 = r.^2;
t9 = x(2,1).*2.0;
t10 = x(3,1).^2;
t11 = x(4,1).^2;
t12 = J_a.*J_p;
t6 = t4.^2;
t13 = t2.^2;
t14 = sin(t9);
t15 = J_a.*m_p.*t4;
t16 = J_p.*m_p.*t4;
t17 = J_p.*m_p.*t8;
t20 = t4.*t7.*t8;
t18 = t6.*t7;
t19 = t13.*t16;
t24 = t13.*t20;
t21 = t13.*t18;
t22 = -t19;
t25 = -t24;
t23 = -t21;
t26 = t12+t15+t16+t17+t18+t20+t22+t23+t25;
t27 = 1.0./t26;

x_dot = zeros(4,1);

x_dot(1,1) = x(3,1);
x_dot(2,1) = x(4,1);
x_dot(3,1) = t27.*(J_p.*tau.*-2.0+B_r.*J_p.*x(3,1).*2.0-m_p.*t4.*tau.*2.0+t14.*t16.*x(3,1).*x(4,1).*2.0+t14.*t18.*x(3,1).*x(4,1).*2.0+B_r.*m_p.*t4.*x(3,1).*2.0+r.*t3.*t5.*t7.*t11.*2.0-g.*r.*t2.*t3.*t4.*t7.*2.0-r.*t2.*t5.*t7.*t10.*t14+B_p.*l_p.*m_p.*r.*t2.*x(4,1).*2.0+J_p.*l_p.*m_p.*r.*t3.*t11.*2.0).*(-1.0./2.0);
x_dot(4,1) = t27.*(B_p.*J_a.*x(4,1).*2.0-t10.*t14.*t15-t10.*t14.*t18-t10.*t14.*t20+t10.*t14.*t21-g.*t3.*t5.*t7.*2.0+t2.*t3.*t11.*t20.*2.0+B_p.*m_p.*t4.*x(4,1).*2.0+B_p.*m_p.*t8.*x(4,1).*2.0-J_a.*g.*l_p.*m_p.*t3.*2.0-B_p.*m_p.*t4.*t13.*x(4,1).*2.0-g.*l_p.*t3.*t7.*t8.*2.0-l_p.*m_p.*r.*t2.*tau.*2.0+g.*t3.*t5.*t7.*t13.*2.0+B_r.*l_p.*m_p.*r.*t2.*x(3,1).*2.0+r.*t2.*t5.*t7.*t14.*x(3,1).*x(4,1).*2.0).*(-1.0./2.0);
